"""Compile high-resolution material oracle into a compact integral-basis table.
No physical print output is relabeled scene-linear: production candidate filters an
emitted scene-radiance base and restores explicit signed XYZ residual.
"""
from pathlib import Path
import json
import numpy as np
from spectral_lab import Lab

# RGB-family hue anchors are artist labels, not ideal physical spectral primaries.
HUES=np.array([29,110,145,195,265,325],float)
WEIGHTS=np.array([[.02,1,1],[.02,.05,1],[1,.02,.8],[1,.05,.02],[1,.6,.02],[.1,1,.02]])

def generate():
    lab=Lab();w=lab.grid
    basis=np.array([np.exp(-.5*((w-c)/sigma)**2) for c,sigma in [(450,38),(545,42),(625,48)]]).T
    B=basis.T@lab.emission_weights
    # Columns are emitted basis spectra's XYZ, not working RGB primaries.
    B=B.T;inverse=np.linalg.inv(B)
    levels=np.linspace(0,1,129)
    table=np.zeros((2,6,129,3,3))
    for model in range(2):
        for family,weights in enumerate(WEIGHTS):
            for i,d in enumerate(levels):
                attenuation=lab.pigment(weights,d*1.5).values if model==0 else lab.dye(weights,d*1.5,.1).values
                table[model,family,i]=(basis*attenuation[:,None]).T@lab.emission_weights
                table[model,family,i]=table[model,family,i].T
    # Interpolation error measured on held-out density levels. KM has square-root
    # concentration behavior at zero; density artist remapping d -> d^2 improves it.
    # Regenerate the pigment table with a squared concentration parameter.
    for family,weights in enumerate(WEIGHTS):
        for i,d in enumerate(levels):
            table[0,family,i]=((basis*lab.pigment(weights,d*d*1.5).values[:,None]).T@lab.emission_weights).T
    errors={}
    for model in range(2):
        worst=0.;rms=[]
        for family,weights in enumerate(WEIGHTS):
            for d in np.linspace(.001,.999,120):
                true=lab.pigment(weights,d*d*1.5).values if model==0 else lab.dye(weights,d*1.5,.1).values
                expected=((basis*true[:,None]).T@lab.emission_weights).T
                z=d*128;i=int(z);approx=(1-(z-i))*table[model,family,i]+(z-i)*table[model,family,i+1]
                # Error normalized by original basis responses to make units explicit.
                err=np.max(np.abs((approx-expected)@inverse));worst=max(worst,float(err));rms.append(err**2)
        errors['KM' if model==0 else 'BeerLambert']={'heldout_matrix_max_error':worst,'rms_matrix_error':float(np.sqrt(np.mean(rms))),'table_levels':129}
    assert max(x['heldout_matrix_max_error'] for x in errors.values())<.0005
    target=Path('include/rendition/generated_spectral_basis.hpp')
    def array(a):return '{'+','.join(array(x) if np.ndim(x) else ('%.12g'%float(x)) for x in a)+'}'
    temporary=target.with_suffix('.hpp.tmp')
    temporary.write_text('// Generated by research/fit_basis.py from original synthetic spectra.\n#pragma once\nnamespace rendition::spectral_basis {\ninline constexpr double B[9]='+array(B.ravel())+';\ninline constexpr double inverseB[9]='+array(inverse.ravel())+';\ninline constexpr float hues[6]='+array(HUES)+';\ninline constexpr double response[2][6][129][9]='+array(table.reshape(2,6,129,9))+';\n}\n')
    temporary.replace(target)
    report={'schema_version':1,'method':'Three emitted Gaussian spectral basis coefficients + exact signed XYZ residual; preintegrated KM/Beer-Lambert response matrices, linear density interpolation','reference_grid':'360–830 nm / 1 nm','basis_parameters_nm':[[450,38],[545,42],[625,48]],'fit':errors,'scene_semantics':'Relative attenuation of reconstructed scene radiance plus unchanged signed residual. Does not simulate a rendered print, viewing illuminant, observer appearance, or a display transform. Spectral reflectance supplies an attenuation trajectory only.','physical_properties_retained':['nonnegative emitted base','spectral wavelength-dependent attenuation','radiometric exposure scaling for fixed selection'],'physical_properties_not_claimed':['unique spectrum recovery','real pigment/film-stock identity','literal material appearance','historical print accuracy'],'limitations':['Only three reconstruction basis functions; residual may dominate extreme colors','Neutral/red anchoring and chroma coupling are creative controls, not physical laws','Scene-relative fitting and visual acceptance still require structured and image validation']}
    out=Path('research/output');out.mkdir(exist_ok=True);(out/'spectral-basis-fit.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
if __name__=='__main__':generate()
