"""Generate portable OFX metadata and Nuke schema from one declarative contract.
No color equations, parameter definitions, or host grade values are generated.
"""
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def generate(check=False):
 schema=json.loads((ROOT/'presentation/control_system.json').read_text())
 def cpp(x):
  if isinstance(x,bool):return 'true' if x else 'false'
  if isinstance(x,(float,int)):return repr(x)
  op,*a=x
  if op=='predicate':return cpp(schema['predicates'][a[0]])
  if op=='value':return 'value('+json.dumps(a[0])+','+repr(a[1])+')'
  if op in ('eq','ne'):return '('+cpp(a[0])+('==' if op=='eq' else '!=')+cpp(a[1])+')'
  if op in ('all','any'):return '('+(' && ' if op=='all' else ' || ').join(cpp(v) for v in a)+')'
  if op=='not':return '!('+cpp(a[0])+')'
  if op in ('min','max'):return 'std::'+op+'(double('+cpp(a[0])+'),double('+cpp(a[1])+'))'
  raise ValueError(op)
 lines=['// Generated by tools/generate_presentation.py; edit presentation/control_system.json.','#pragma once','#include "operators.hpp"','namespace rendition {']
 fragments=schema['host_presentation']['Nuke']['host_name_fragments']
 lines.append('inline bool presentationUsesHostLinks(const std::string &hostName) {return '+ ' || '.join('hostName.find('+json.dumps(f)+')!=std::string::npos' for f in fragments)+';}')
 lines+=['inline std::string uiPage(Effect e,const Parameter &d) {']
 for effect in schema['effects'].values():
  lines.append(' if(e==Effect::'+effect['name']+') {')
  for item in effect['controls']:
   if 'default' in item:lines.append('  if(d.id=='+json.dumps(item['id'])+')return '+json.dumps(item['page'])+';')
  lines.append(' }')
 lines+=[' return d.group;','}']
 for function,field in [('presentationEnabled','native_enabled'),('presentationSecret','native_secret')]:
  lines.append('template<class Value> bool '+function+'(Effect e,const std::string &id,Value value) {')
  for effect in schema['effects'].values():
   lines.append(' if(e==Effect::'+effect['name']+') {')
   for item in effect['controls']:lines.append('  if(id=='+json.dumps(item['id'])+')return '+cpp(item[field])+';')
   lines.append(' }')
  lines+=[' return '+('true' if field=='native_enabled' else 'false')+';','}']
 lines.append('template<class Value> bool presentationRange(Effect e,const std::string &id,Value value,double &lo,double &hi) {')
 for effect in schema['effects'].values():
  for item in effect['controls']:
   if 'display_range' in item:lines.append(' if(e==Effect::'+effect['name']+' && id=='+json.dumps(item['id'])+') {lo='+cpp(item['display_range'][0])+';hi='+cpp(item['display_range'][1])+';return true;}')
 lines+=[' return false;','}', 'inline bool customCoordinate(const std::string &id) {return id=="rx" || id=="ry" || id=="gx" || id=="gy" || id=="bx" || id=="by" || id=="wx" || id=="wy";}','}']
 outputs={ROOT/'integrations/nuke/artist-groups.json':json.dumps(schema['groups'],indent=2)+'\n',ROOT/'include/rendition/ui_layout.hpp':'\n'.join(lines)+'\n',ROOT/'integrations/nuke/presentation-schema.json':json.dumps(schema,indent=2)+'\n'}
 for path,text in outputs.items():
  if check:
   if not path.exists() or path.read_text()!=text:raise SystemExit('Stale generated presentation: '+str(path))
  else:path.write_text(text)
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');generate(parser.parse_args().check)
