"""Generate shared CPU/Metal parameter slots from the authoritative descriptors."""
from pathlib import Path
import _rendition as c
ids=sorted({p['id'] for e in range(8) for p in c.parameters(e)})
out=Path('include/rendition/kernel_parameters.hpp')
out.write_text('// Generated by tools/generate_kernel_parameters.py; parameter names are stable.\n#pragma once\nnamespace rendition_kernel {\nenum ParameterSlot {\n'+''.join(' P_'+key+' = '+str(i)+',\n' for i,key in enumerate(ids))+' P_COUNT = '+str(len(ids))+'\n};\n#ifndef __METAL_VERSION__\ninline constexpr const char* parameterNames[P_COUNT] = {'+','.join('"'+key+'"' for key in ids)+'};\n#endif\n}\n')
