"""Regenerate checked-in D50 ColorChecker XYZ data without invoking an OFX host."""
from pathlib import Path
import colour
chart=colour.CCS_COLOURCHECKERS['ColorChecker 2005']
text='// Generated by tools/generate_chart.py from Colour 0.4.7 ColorChecker 2005 xyY, D50.\n'
text+='constexpr double chartWhiteX=%r,chartWhiteY=%r;\n'%tuple(chart.illuminant)
text+='constexpr float chartXYZ[24][3]={\n'
for x in chart.data.values():text+='{'+','.join('%.9gf'%v for v in colour.xyY_to_XYZ(x))+'},\n'
text+='};\n';Path('src/ofx/chart.inc').write_text(text)
